variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'frontendaccountcreationregistry'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'frontendaccountcreationregistry'
  serviceName: 'prdrwdwebwa1402'
